version: "3.8"

services:
  frontend:
    build:
      context: ./task-reminder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./task-reminder/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
