version: "3.8"

services:
  frontend:
    build:
      context: ./task-reminder
      dockerfile: Dockerfile
    ports:
      - "5174:80"

  backend:
    build:
      context: ./task-reminder/backend
      dockerfile: Dockerfile
    ports:
      - "6000:8000"
